<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.apache.tomcat</groupId>
    <artifactId>tomcat-parent</artifactId>
    <version>10.1.54</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <artifactId>tomcat-bootstrap</artifactId>
  <description>Apache Tomcat - Bootstrap (subset of catalina classes for the launcher)</description>
  <dependencies>
    <dependency>
      <groupId>org.apache.tomcat</groupId>
      <artifactId>tomcat-catalina</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat</groupId>
      <artifactId>tomcat-util</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals><goal>shade</goal></goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <artifactSet>
                <includes>
                  <include>org.apache.tomcat:tomcat-catalina</include>
                  <include>org.apache.tomcat:tomcat-util</include>
                </includes>
              </artifactSet>
              <filters>
                <filter>
                  <artifact>org.apache.tomcat:tomcat-catalina</artifact>
                  <includes>
                    <include>org/apache/catalina/startup/Bootstrap.class</include>
                    <include>org/apache/catalina/startup/catalina.properties</include>
                    <include>org/apache/catalina/startup/CatalinaProperties.class</include>
                    <include>org/apache/catalina/startup/CatalinaProperties$*.class</include>
                    <include>org/apache/catalina/startup/ClassLoaderFactory.class</include>
                    <include>org/apache/catalina/startup/ClassLoaderFactory$*.class</include>
                    <include>org/apache/catalina/startup/Constants.class</include>
                    <include>org/apache/catalina/startup/SafeForkJoinWorkerThreadFactory.class</include>
                    <include>org/apache/catalina/startup/SafeForkJoinWorkerThreadFactory$*.class</include>
                    <include>org/apache/catalina/startup/Tool.class</include>
                    <include>org/apache/catalina/startup/Tool$*.class</include>
                    <include>org/apache/catalina/security/SecurityClassLoad.class</include>
                    <include>org/apache/catalina/security/SecurityClassLoad$*.class</include>
                    <include>org/apache/catalina/webresources/war/**</include>
                  </includes>
                </filter>
                <filter>
                  <artifact>org.apache.tomcat:tomcat-util</artifact>
                  <includes>
                    <include>org/apache/tomcat/util/buf/UriUtil.class</include>
                    <include>org/apache/tomcat/util/buf/UriUtil$*.class</include>
                  </includes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
